const FETCH_PLACES_REQUEST = "FETCH_PLACES_REQUEST";
const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
const FETCH_PLACES_ERROR = "FETCH_PLACES_ERROR";
const ADD_PLACE = "ADD_PLACE";
const TOGGLE_PLACE = "TOGGLE_PLACE";
const SET_FILTER = "SET_FILTER";

export default {
  FETCH_PLACES_REQUEST,
  FETCH_PLACES_SUCCESS,
  FETCH_PLACES_ERROR,
  ADD_PLACE,
  TOGGLE_PLACE,
  SET_FILTER
};
